GET https://localhost:4300/api/compromissos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMWVmNDU5NC03MmE4LTQ1YzQtOWM4OS0wOGRjZjJiYzk4ZTQiLCJlbWFpbCI6Imp1bmluaG9AZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJqdW5pbmhvIiwiZ2l2ZW5fbmFtZSI6Imp1bmluaG8iLCJuYmYiOjE3Mjk3ODU4NzcsImV4cCI6MTczMDIxNzg3NywiaWF0IjoxNzI5Nzg1ODc3LCJpc3MiOiJlQWdlbmRhIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdCJ9.kK8E0wOuLalTZL_xIvcCPZkD81ZMB106K4m7iN1Lecw

